### ISSUE TITLE
Getting error: If you wish to make changes to it, then you will have to pass the --allow-live flag

### ISSUE THREAD

**Issue by PixMech** [WorkshopCLI/workshop-advanced-gulp#27]
I'm getting the following error when deploying the theme to shoplift store:

`If you wish to make changes to it, then you will have to pass the --allow-live flag`

**Comment by salexzee** [comment]
We're using themekit for some of the behind the scenes connections with Shopify. By default, you cannot use themekit's `watch` or `deploy` commands on the live theme. This is to prevent people from messing up the live theme and to encourage the use of development themes.

The error messages is a little misleading since we're not using the themekit CLI, we're using the integrated node package. So passing --allow-live doesn't actually have any impact.

I'll look further into this when I get a chance.

**Comment by akvdcode** [comment]
Have any workaround this?

**Comment by salexzee** [comment]
Yes this is fixed in this commit https://github.com/WorkshopCLI/workshop-advanced-gulp/commit/b7c8eeb1d699dd4fc22bbe9653e7b6b7860aef9c
