### ISSUE TITLE
Theme Language

### ISSUE THREAD

**Issue by kuduz0vic** [WorkshopCLI/workshop-advanced-gulp#30]
So basically inside the theme code there is a file en.default.json, and basically there is no way to make the theme have English language. I tried copying en.default.json from debut theme and pasting it into my own theme, but after I do yarn start I have to either first save the file, or it just completely erases the content. I also tried doing it from the Shopify code editor with no success. So basically I'm just looking to add basic English to my theme, so I could use the Shopify features like newsletter and similar.

**Comment by salexzee** [comment]
I'll take a look at locale file uploads and see if there's a bug there.

**Comment by kuduz0vic** [comment]
Alright, thanks a lot.

**Comment by salexzee** [comment]
@kuduz0vic I'm not seeing any issues with uploading locales using this workflow. This workflow doesn't work to keep locales in sync with what's in your storefront, so you should be careful when making locale changes locally if you're working on a live/currently in use storefront. For more information about locales see Shopify's documentation here: https://shopify.dev/themes/architecture/locales

**Comment by salexzee** [comment]
Reopening this. I think the issue you're running into has to do with the fact that `yarn start` automatically re-deploys all files. This will cause "data storage" type files to be overridden by whatever's in your theme code. To resolve this I think what I'll do is remove all of the build stuff from `yarn start`. `yarn start` will simply open the store and run the watcher. This way we don't always re-upload files that have already been uploaded.

This will cause a big change in how things work. If you make changes to a file while the watcher isn't running, it will not be automatically uploaded the next time you run `yarn start`. You'll have to re-save the file to make sure it gets uploaded.

I'm comfortable with this change, since Online Store 2.0 json templates will be "data storage" files now and so for now this seems like the best short term change.

**Comment by salexzee** [comment]
Closing this again. It will be taken care of in this issue https://github.com/WorkshopCLI/workshop-advanced-gulp/issues/32
